repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--sl"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,E501,B008,B950
          - --select=C,E,F,W,B,B950
          - --max-complexity=18
          - --ignore=B008,B950,W503
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - tomli >= 0.2.6, < 2.0.0
          - types-typed-ast >= 1.4.1
          - types-PyYAML
          - types-requests

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: detect-private-key

  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: poetry run python manage.py test
        always_run: true
        pass_filenames: false
        language: system
